version: '3.5'

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=bus_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'

  flask-api:
    container_name: app-app
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "db"